// 2026/04/15 00:00:30 MetaModel - Archivo generado automaticamente, NO modificar
ATTRDEFS = {
		1: {caption:"[OLD] #NRORAS",categoryId:"1",type:"I",validation:"none" },
		2: {caption:"[OLD] CAU",categoryId:"1",type:"S",validation:"none" },
		3: {caption:"[OLD] COD",categoryId:"1",type:"S",validation:"none" },
		4: {caption:"[OLD] COM1",categoryId:"1",type:"S",validation:"none" },
		5: {caption:"[OLD] COM2",categoryId:"1",type:"D",validation:"none" },
		6: {caption:"[OLD] DBA1",categoryId:"1",type:"S",validation:"none" },
		7: {caption:"[OLD] DBA11",categoryId:"1",type:"S",validation:"none" },
		8: {caption:"[OLD] DBA2",categoryId:"1",type:"S",validation:"none" },
		9: {caption:"[OLD] DBA22",categoryId:"1",type:"S",validation:"none" },
		10: {caption:"[OLD] FL1",categoryId:"1",type:"S",validation:"none" },
		11: {caption:"[OLD] FL2",categoryId:"1",type:"S",validation:"none" },
		12: {caption:"[OLD] FL3",categoryId:"1",type:"S",validation:"none" },
		13: {caption:"[OLD] H",categoryId:"1",type:"S",validation:"none" },
		14: {caption:"[OLD] ID",categoryId:"1",type:"S",validation:"none" },
		15: {caption:"[OLD] ID11",categoryId:"1",type:"S",validation:"none" },
		16: {caption:"[OLD] ID22",categoryId:"1",type:"S",validation:"none" },
		17: {caption:"[OLD] IDAUX1",categoryId:"1",type:"S",validation:"none" },
		18: {caption:"[OLD] IDAUX2",categoryId:"1",type:"S",validation:"none" },
		19: {caption:"[OLD] IDDR",categoryId:"1",type:"S",validation:"none" },
		20: {caption:"[OLD] IDP",categoryId:"1",type:"S",validation:"none" },
		21: {caption:"[OLD] IDPA",categoryId:"1",type:"S",validation:"none" },
		22: {caption:"[OLD] LAY",categoryId:"1",type:"S",validation:"none" },
		23: {caption:"[OLD] MOD",categoryId:"1",type:"S",validation:"none" },
		24: {caption:"[OLD] N1",categoryId:"1",type:"S",validation:"none" },
		25: {caption:"[OLD] N2",categoryId:"1",type:"S",validation:"none" },
		26: {caption:"[OLD] PR",categoryId:"1",type:"S",validation:"none" },
		27: {caption:"[OLD] PTE",categoryId:"1",type:"S",validation:"none" },
		28: {caption:"[OLD] RAS1",categoryId:"1",type:"S",validation:"none" },
		29: {caption:"[OLD] RAS2",categoryId:"1",type:"S",validation:"none" },
		30: {caption:"[OLD] S1",categoryId:"1",type:"S",validation:"none" },
		31: {caption:"[OLD] TOM",categoryId:"1",type:"S",validation:"none" },
		32: {caption:"[OLD] DBA",categoryId:"1",type:"S",validation:"none" },
		33: {caption:"[OLD] #CCC",categoryId:"1",type:"I",validation:"none" },
		34: {caption:"[OLD] ACO",categoryId:"1",type:"S",validation:"none" },
		35: {caption:"[OLD] CEN",categoryId:"1",type:"S",validation:"none" },
		36: {caption:"[OLD] SAL",categoryId:"1",type:"S",validation:"none" },
		37: {caption:"[OLD] SUM1",categoryId:"1",type:"S",validation:"none" },
		38: {caption:"[OLD] SUM2",categoryId:"1",type:"S",validation:"none" },
		39: {caption:"[OLD] IDB",categoryId:"1",type:"S",validation:"none" },
		40: {caption:"[OLD] DBA_ASC",categoryId:"1",type:"S",validation:"none" },
		41: {caption:"[OLD] FA",categoryId:"1",type:"S",validation:"none" },
		42: {caption:"[OLD] FS",categoryId:"1",type:"S",validation:"none" },
		43: {caption:"[OLD] ID_ASC",categoryId:"1",type:"S",validation:"none" },
		44: {caption:"[OLD] PAIG",categoryId:"1",type:"S",validation:"none" },
		45: {caption:"[OLD] TAB",categoryId:"1",type:"S",validation:"none" },
		46: {caption:"[OLD] CAJA",categoryId:"1",type:"S",validation:"none" },
		48: {caption:"[OLD] CENVIE",categoryId:"1",type:"S",validation:"none" },
		55: {caption:"[OLD] MED1",categoryId:"1",type:"S",validation:"none" },
		56: {caption:"[OLD] MED2",categoryId:"1",type:"S",validation:"none" },
		57: {caption:"[OLD] MED3",categoryId:"1",type:"S",validation:"none" },
		58: {caption:"[OLD] SALVIE",categoryId:"1",type:"S",validation:"none" },
		59: {caption:"[OLD] SUMVIE",categoryId:"1",type:"S",validation:"none" },
		60: {caption:"[OLD] DBA3",categoryId:"1",type:"S",validation:"none" },
		61: {caption:"[OLD] IDT1",categoryId:"1",type:"S",validation:"none" },
		62: {caption:"[OLD] IDT2",categoryId:"1",type:"S",validation:"none" },
		63: {caption:"[OLD] NOM",categoryId:"1",type:"S",validation:"none" },
		64: {caption:"[OLD] PT",categoryId:"1",type:"S",validation:"none" },
		65: {caption:"[OLD] DES",categoryId:"1",type:"S",validation:"none" },
		66: {caption:"[OLD] ID1",categoryId:"1",type:"S",validation:"none" },
		67: {caption:"[OLD] TRIF",categoryId:"1",type:"S",validation:"none" },
		68: {caption:"[OLD] EMPALME",categoryId:"1",type:"S",validation:"none" },
		69: {caption:"[OLD] REIF",categoryId:"1",type:"S",validation:"none" },
		70: {caption:"[OLD] FLPI",categoryId:"1",type:"S",validation:"none" },
		71: {caption:"[OLD] EST",categoryId:"1",type:"S",validation:"none" },
		72: {caption:"[OLD] ALIM",categoryId:"1",type:"S",validation:"none" },
		73: {caption:"[OLD] NAB",categoryId:"1",type:"S",validation:"none" },
		74: {caption:"[OLD] NAR",categoryId:"1",type:"S",validation:"none" },
		76: {caption:"[OLD] OBSERVACIONES",categoryId:"1",type:"S",validation:"none" },
		77: {caption:"[OLD] CAMBIO",categoryId:"1",type:"S",validation:"none" },
		78: {caption:"[OLD] REF",categoryId:"1",type:"S",validation:"none" },
		79: {caption:"[OLD] ADD",categoryId:"1",type:"S",validation:"none" },
		80: {caption:"[OLD] TIP",categoryId:"1",type:"S",validation:"none" },
		81: {caption:"[OLD] MED",categoryId:"1",type:"S",validation:"none" },
		82: {caption:"[OLD] CAL",categoryId:"1",type:"S",validation:"none" },
		83: {caption:"[OLD] PAST",categoryId:"1",type:"S",validation:"none" },
		84: {caption:"[OLD] DBAPA",categoryId:"1",type:"S",validation:"none" },
		85: {caption:"[OLD] REC",categoryId:"1",type:"S",validation:"none" },
		86: {caption:"[OLD] SIM1",categoryId:"1",type:"S",validation:"none" },
		87: {caption:"[OLD] SIM2",categoryId:"1",type:"S",validation:"none" },
		88: {caption:"[OLD] C1",categoryId:"1",type:"S",validation:"none" },
		89: {caption:"[OLD] SIM",categoryId:"1",type:"S",validation:"none" },
		90: {caption:"[OLD] SUM",categoryId:"1",type:"S",validation:"none" },
		94: {caption:"[OLD] PLANO",categoryId:"1",type:"S",validation:"none" },
		95: {caption:"[OLD] RAS3",categoryId:"1",type:"S",validation:"none" },
		96: {caption:"[OLD] RAS4",categoryId:"1",type:"S",validation:"none" },
		102: {caption:"[OLD] SAL1",categoryId:"1",type:"S",validation:"none" },
		104: {caption:"[OLD] CAR",categoryId:"1",type:"S",validation:"none" },
		105: {caption:"[OLD] N3",categoryId:"1",type:"S",validation:"none" },
		106: {caption:"[OLD] POT",categoryId:"1",type:"R",validation:"none" },
		107: {caption:"[OLD] DBAREL",categoryId:"1",type:"S",validation:"none" },
		108: {caption:"[OLD] NSUM",categoryId:"1",type:"I",validation:"none" },
		109: {caption:"[OLD] MONT",categoryId:"1",type:"S",validation:"none" },
		110: {caption:"[OLD] CT",categoryId:"1",type:"S",validation:"none" },
		111: {caption:"[OLD] ASERV",categoryId:"1",type:"S",validation:"none" },
		112: {caption:"[OLD] FLGSERV",categoryId:"1",type:"S",validation:"none" },
		113: {caption:"[OLD] ALTURA",categoryId:"1",type:"S",validation:"none" },
		114: {caption:"[OLD] CCC1",categoryId:"1",type:"S",validation:"none" },
		115: {caption:"[OLD] CCC2",categoryId:"1",type:"S",validation:"none" },
		116: {caption:"[OLD] BARRA",categoryId:"1",type:"S",validation:"none" },
		117: {caption:"[OLD] IDN",categoryId:"1",type:"S",validation:"none" },
		118: {caption:"[OLD] KARMA",categoryId:"1",type:"S",validation:"none" },
		119: {caption:"[OLD] SEG",categoryId:"1",type:"S",validation:"none" },
		120: {caption:"[OLD] TRA",categoryId:"1",type:"S",validation:"none" },
		121: {caption:"[OLD] SACAR",categoryId:"1",type:"S",validation:"none" },
		122: {caption:"[OLD] NROSECC",categoryId:"1",type:"S",validation:"none" },
		123: {caption:"[OLD] IDM",categoryId:"1",type:"S",validation:"none" },
		124: {caption:"[OLD] CAB",categoryId:"1",type:"S",validation:"none" },
		125: {caption:"[OLD] NONO",categoryId:"1",type:"S",validation:"none" },
		126: {caption:"[OLD] NOSEG",categoryId:"1",type:"S",validation:"none" },
		127: {caption:"[OLD] LGEO",categoryId:"1",type:"S",validation:"none" },
		128: {caption:"[OLD] EXT1",categoryId:"1",type:"S",validation:"none" },
		129: {caption:"[OLD] IDSEG",categoryId:"1",type:"S",validation:"none" },
		130: {caption:"[OLD] HTXT",categoryId:"1",type:"S",validation:"none" },
		131: {caption:"[OLD] SUB",categoryId:"1",type:"S",validation:"none" },
		132: {caption:"[OLD] CDI",categoryId:"1",type:"S",validation:"none" },
		133: {caption:"[OLD] CRE",categoryId:"1",type:"S",validation:"none" },
		134: {caption:"[OLD] ALIM1",categoryId:"1",type:"S",validation:"none" },
		135: {caption:"[OLD] ALIM2",categoryId:"1",type:"S",validation:"none" },
		136: {caption:"[OLD] ANIO",categoryId:"1",type:"S",validation:"none" },
		137: {caption:"[OLD] COB",categoryId:"1",type:"S",validation:"none" },
		138: {caption:"[OLD] NOMVIE",categoryId:"1",type:"S",validation:"none" },
		139: {caption:"[OLD] SUA",categoryId:"1",type:"S",validation:"none" },
		140: {caption:"[OLD] NOMCAB",categoryId:"1",type:"S",validation:"none" },
		141: {caption:"[OLD] IDS",categoryId:"1",type:"S",validation:"none" },
		142: {caption:"[OLD] FECHA",categoryId:"1",type:"D",validation:"none" },
		143: {caption:"[OLD] NOMCON",categoryId:"1",type:"S",validation:"none" },
		144: {caption:"[OLD] TXT1",categoryId:"1",type:"S",validation:"none" },
		145: {caption:"[OLD] TXT2",categoryId:"1",type:"S",validation:"none" },
		146: {caption:"[OLD] PT1",categoryId:"1",type:"S",validation:"none" },
		147: {caption:"[OLD] PT2",categoryId:"1",type:"S",validation:"none" },
		148: {caption:"[OLD] ANGULO",categoryId:"1",type:"S",validation:"none" },
		149: {caption:"[OLD] SEGN",categoryId:"1",type:"S",validation:"none" },
		150: {caption:"[OLD] TRAN",categoryId:"1",type:"S",validation:"none" },
		151: {caption:"[OLD] CABN",categoryId:"1",type:"S",validation:"none" },
		152: {caption:"[OLD] LREAL",categoryId:"1",type:"S",validation:"none" },
		153: {caption:"[OLD] #CAB",categoryId:"1",type:"S",validation:"none" },
		154: {caption:"[OLD] #CABN",categoryId:"1",type:"S",validation:"none" },
		155: {caption:"[OLD] LGEON",categoryId:"1",type:"S",validation:"none" },
		156: {caption:"[OLD] LGEOV",categoryId:"1",type:"S",validation:"none" },
		157: {caption:"[OLD] NOM2",categoryId:"1",type:"S",validation:"none" },
		158: {caption:"[OLD] MARCA",categoryId:"1",type:"S",validation:"none" },
		159: {caption:"[OLD] COND",categoryId:"1",type:"S",validation:"none" },
		160: {caption:"[OLD] OBS",categoryId:"1",type:"S",validation:"none" },
		161: {caption:"[OLD] PADRE",categoryId:"1",type:"S",validation:"none" },
		162: {caption:"[OLD] TRAB1",categoryId:"1",type:"S",validation:"none" },
		163: {caption:"[OLD] TRAB2",categoryId:"1",type:"S",validation:"none" },
		164: {caption:"[OLD] BOBINA",categoryId:"1",type:"I",validation:"none" },
		165: {caption:"[OLD] AÑO_INST",categoryId:"1",type:"S",validation:"none" },
		166: {caption:"[OLD] SECC",categoryId:"1",type:"S",validation:"none" },
		167: {caption:"[OLD] PIN",categoryId:"1",type:"S",validation:"none" },
		168: {caption:"[OLD] CANTDR",categoryId:"1",type:"S",validation:"none" },
		169: {caption:"[OLD] NOMORI",categoryId:"1",type:"S",validation:"none" },
		170: {caption:"[OLD] NOMDR",categoryId:"1",type:"S",validation:"none" },
		171: {caption:"[OLD] ESDR",categoryId:"1",type:"S",validation:"none" },
		172: {caption:"[SIPRE2] UMA",categoryId:"1",type:"S",validation:"none" },
		173: {caption:"[OLD] UMAV",categoryId:"1",type:"S",validation:"none" },
		174: {caption:"[OLD] IDCT",categoryId:"1",type:"S",validation:"none" },
		175: {caption:"[OLD] IDPO",categoryId:"1",type:"S",validation:"none" },
		176: {caption:"[OLD] IDEM",categoryId:"1",type:"S",validation:"none" },
		177: {caption:"[OLD] IDEX",categoryId:"1",type:"S",validation:"none" },
		178: {caption:"[OLD] IDDI",categoryId:"1",type:"S",validation:"none" },
		179: {caption:"[OLD] IDRA",categoryId:"1",type:"S",validation:"none" },
		180: {caption:"[OLD] IDSE",categoryId:"1",type:"S",validation:"none" },
		181: {caption:"[OLD] IDCB",categoryId:"1",type:"S",validation:"none" },
		182: {caption:"[OLD] IDCG",categoryId:"1",type:"S",validation:"none" },
		183: {caption:"[OLD] IDCD",categoryId:"1",type:"S",validation:"none" },
		184: {caption:"[OLD] IDAL",categoryId:"1",type:"S",validation:"none" },
		185: {caption:"[OLD] TENSION",categoryId:"1",type:"S",validation:"none" },
		186: {caption:"[OLD] TECNOLOGIA",categoryId:"1",type:"S",validation:"none" },
		187: {caption:"[OLD] TERRENO",categoryId:"1",type:"S",validation:"none" },
		188: {caption:"[OLD] CTL",categoryId:"1",type:"S",validation:"none" },
		189: {caption:"[OLD] FEC_INST",categoryId:"1",type:"D",validation:"none" },
		190: {caption:"[OLD] ENTIDAD",categoryId:"1",type:"S",validation:"none" },
		192: {caption:"[OLD] NO2",categoryId:"1",type:"S",validation:"none" },
		193: {caption:"[OLD] DEPBLQ",categoryId:"1",type:"S",validation:"none" },
		194: {caption:"[OLD] H1",categoryId:"1",type:"S",validation:"none" },
		195: {caption:"[OLD] H2",categoryId:"1",type:"S",validation:"none" },
		196: {caption:"[OLD] H3",categoryId:"1",type:"S",validation:"none" },
		197: {caption:"[OLD] H4",categoryId:"1",type:"S",validation:"none" },
		198: {caption:"[OLD] CE",categoryId:"1",type:"S",validation:"none" },
		199: {caption:"[OLD] ZSEG",categoryId:"1",type:"S",validation:"none" },
		200: {caption:"[OLD] ZTRA",categoryId:"1",type:"S",validation:"none" },
		201: {caption:"[OLD] ZID",categoryId:"1",type:"S",validation:"none" },
		202: {caption:"[OLD] ZALIM",categoryId:"1",type:"S",validation:"none" },
		203: {caption:"[OLD] PLCO",categoryId:"1",type:"S",validation:"none" },
		204: {caption:"[OLD] TIPOICC",categoryId:"1",type:"S",validation:"none" },
		205: {caption:"[OLD] TIPO",categoryId:"1",type:"S",validation:"none" },
		206: {caption:"[OLD] DIGITALIZO",categoryId:"1",type:"S",validation:"none" },
		207: {caption:"[OLD] H:",categoryId:"1",type:"S",validation:"none" },
		208: {caption:"[OLD] GRILLA",categoryId:"1",type:"S",validation:"none" },
		209: {caption:"[OLD] PIQUETE",categoryId:"1",type:"S",validation:"none" },
		210: {caption:"[OLD] DER",categoryId:"1",type:"S",validation:"none" },
		211: {caption:"[OLD] SUBESTACION",categoryId:"1",type:"S",validation:"none" },
		212: {caption:"[OLD] ESTADO",categoryId:"1",type:"S",validation:"none" },
		213: {caption:"[OLD] FECHAPS",categoryId:"1",type:"D",validation:"none" },
		214: {caption:"[OLD] FL4",categoryId:"1",type:"S",validation:"none" },
		215: {caption:"[OLD] FL5",categoryId:"1",type:"S",validation:"none" },
		216: {caption:"[OLD] POSINT",categoryId:"1",type:"S",validation:"none" },
		217: {caption:"[OLD] IDPQ",categoryId:"1",type:"S",validation:"none" },
		218: {caption:"[OLD] IDPC",categoryId:"1",type:"S",validation:"none" },
		219: {caption:"[OLD] ESCALA",categoryId:"1",type:"I",validation:"none" },
		220: {caption:"[OLD] ORDENPTOS",categoryId:"1",type:"S",validation:"none" },
		221: {caption:"[OLD] DESMALEZAR",categoryId:"1",type:"S",validation:"none" },
		222: {caption:"[OLD] PARTIDO",categoryId:"1",type:"S",validation:"none" },
		223: {caption:"[OLD] PARTIDOV",categoryId:"1",type:"I",validation:"none" },
		224: {caption:"[OLD] IDMO",categoryId:"1",type:"I",validation:"none" },
		225: {caption:"[OLD] IDJU",categoryId:"1",type:"I",validation:"none" },
		226: {caption:"[OLD] IDCTMO",categoryId:"1",type:"I",validation:"none" },
		227: {caption:"[OLD] IDMA",categoryId:"1",type:"I",validation:"none" },
		228: {caption:"[OLD] IDNO",categoryId:"1",type:"I",validation:"none" },
		229: {caption:"[OLD] IDOL",categoryId:"1",type:"I",validation:"none" },
		230: {caption:"[OLD] IDPI",categoryId:"1",type:"I",validation:"none" },
		231: {caption:"[OLD] IDCTJU",categoryId:"1",type:"I",validation:"none" },
		232: {caption:"[OLD] IDCTMA",categoryId:"1",type:"I",validation:"none" },
		233: {caption:"[OLD] IDCTNO",categoryId:"1",type:"I",validation:"none" },
		234: {caption:"[OLD] IDCTOL",categoryId:"1",type:"I",validation:"none" },
		235: {caption:"[OLD] IDCTPI",categoryId:"1",type:"I",validation:"none" },
		236: {caption:"[OLD] IDPOMO",categoryId:"1",type:"I",validation:"none" },
		237: {caption:"[OLD] IDPOJU",categoryId:"1",type:"I",validation:"none" },
		238: {caption:"[OLD] IDPOMA",categoryId:"1",type:"I",validation:"none" },
		239: {caption:"[OLD] IDPONO",categoryId:"1",type:"I",validation:"none" },
		240: {caption:"[OLD] IDPOOL",categoryId:"1",type:"I",validation:"none" },
		241: {caption:"[OLD] IDPOPI",categoryId:"1",type:"I",validation:"none" },
		242: {caption:"[OLD] IDEMMO",categoryId:"1",type:"I",validation:"none" },
		243: {caption:"[OLD] IDEMJU",categoryId:"1",type:"I",validation:"none" },
		244: {caption:"[OLD] IDEMMA",categoryId:"1",type:"I",validation:"none" },
		245: {caption:"[OLD] IDEMNO",categoryId:"1",type:"I",validation:"none" },
		246: {caption:"[OLD] IDEMOL",categoryId:"1",type:"I",validation:"none" },
		247: {caption:"[OLD] IDEMPI",categoryId:"1",type:"I",validation:"none" },
		248: {caption:"[OLD] IDEXMO",categoryId:"1",type:"I",validation:"none" },
		249: {caption:"[OLD] IDEXJU",categoryId:"1",type:"I",validation:"none" },
		250: {caption:"[OLD] IDEXMA",categoryId:"1",type:"I",validation:"none" },
		251: {caption:"[OLD] IDEXNO",categoryId:"1",type:"I",validation:"none" },
		252: {caption:"[OLD] IDEXOL",categoryId:"1",type:"I",validation:"none" },
		253: {caption:"[OLD] IDEXPI",categoryId:"1",type:"I",validation:"none" },
		254: {caption:"[OLD] IDDIMO",categoryId:"1",type:"I",validation:"none" },
		255: {caption:"[OLD] IDDIJU",categoryId:"1",type:"I",validation:"none" },
		256: {caption:"[OLD] IDDIMA",categoryId:"1",type:"I",validation:"none" },
		257: {caption:"[OLD] IDDINO",categoryId:"1",type:"I",validation:"none" },
		258: {caption:"[OLD] IDDIOL",categoryId:"1",type:"I",validation:"none" },
		259: {caption:"[OLD] IDDIPI",categoryId:"1",type:"I",validation:"none" },
		260: {caption:"[OLD] IDRAMO",categoryId:"1",type:"I",validation:"none" },
		261: {caption:"[OLD] IDRAJU",categoryId:"1",type:"I",validation:"none" },
		262: {caption:"[OLD] IDRAMA",categoryId:"1",type:"I",validation:"none" },
		263: {caption:"[OLD] IDRANO",categoryId:"1",type:"I",validation:"none" },
		264: {caption:"[OLD] IDRAOL",categoryId:"1",type:"I",validation:"none" },
		265: {caption:"[OLD] IDRAPI",categoryId:"1",type:"I",validation:"none" },
		266: {caption:"[OLD] IDSEMO",categoryId:"1",type:"I",validation:"none" },
		267: {caption:"[OLD] IDSEJU",categoryId:"1",type:"I",validation:"none" },
		268: {caption:"[OLD] IDSEMA",categoryId:"1",type:"I",validation:"none" },
		269: {caption:"[OLD] IDSENO",categoryId:"1",type:"I",validation:"none" },
		270: {caption:"[OLD] IDSEOL",categoryId:"1",type:"I",validation:"none" },
		271: {caption:"[OLD] IDSEPI",categoryId:"1",type:"I",validation:"none" },
		272: {caption:"[OLD] IDCBMO",categoryId:"1",type:"I",validation:"none" },
		273: {caption:"[OLD] IDCBJU",categoryId:"1",type:"I",validation:"none" },
		274: {caption:"[OLD] IDCBMA",categoryId:"1",type:"I",validation:"none" },
		275: {caption:"[OLD] IDCBNO",categoryId:"1",type:"I",validation:"none" },
		276: {caption:"[OLD] IDCBOL",categoryId:"1",type:"I",validation:"none" },
		277: {caption:"[OLD] IDCBPI",categoryId:"1",type:"I",validation:"none" },
		278: {caption:"[OLD] IDCGMO",categoryId:"1",type:"I",validation:"none" },
		279: {caption:"[OLD] IDCGJU",categoryId:"1",type:"I",validation:"none" },
		280: {caption:"[OLD] IDCGMA",categoryId:"1",type:"I",validation:"none" },
		281: {caption:"[OLD] IDCGNO",categoryId:"1",type:"I",validation:"none" },
		282: {caption:"[OLD] IDCGOL",categoryId:"1",type:"I",validation:"none" },
		283: {caption:"[OLD] IDCGPI",categoryId:"1",type:"I",validation:"none" },
		284: {caption:"[OLD] IDCDMO",categoryId:"1",type:"I",validation:"none" },
		285: {caption:"[OLD] IDCDJU",categoryId:"1",type:"I",validation:"none" },
		286: {caption:"[OLD] IDCDMA",categoryId:"1",type:"I",validation:"none" },
		287: {caption:"[OLD] IDCDNO",categoryId:"1",type:"I",validation:"none" },
		288: {caption:"[OLD] IDCDOL",categoryId:"1",type:"I",validation:"none" },
		289: {caption:"[OLD] IDCDPI",categoryId:"1",type:"I",validation:"none" },
		290: {caption:"[OLD] IDALMO",categoryId:"1",type:"I",validation:"none" },
		291: {caption:"[OLD] IDALJU",categoryId:"1",type:"I",validation:"none" },
		292: {caption:"[OLD] IDALMA",categoryId:"1",type:"I",validation:"none" },
		293: {caption:"[OLD] IDALNO",categoryId:"1",type:"I",validation:"none" },
		294: {caption:"[OLD] IDALOL",categoryId:"1",type:"I",validation:"none" },
		295: {caption:"[OLD] IDALPI",categoryId:"1",type:"I",validation:"none" },
		296: {caption:"[OLD] NOMCTNO",categoryId:"1",type:"S",validation:"none" },
		297: {caption:"[OLD] NOMPONO",categoryId:"1",type:"S",validation:"none" },
		298: {caption:"[OLD] NOMEMNO",categoryId:"1",type:"S",validation:"none" },
		299: {caption:"[OLD] NOMEXNO",categoryId:"1",type:"S",validation:"none" },
		300: {caption:"[OLD] NOMDINO",categoryId:"1",type:"S",validation:"none" },
		301: {caption:"[OLD] NOMRANO",categoryId:"1",type:"S",validation:"none" },
		302: {caption:"[OLD] NOMSENO",categoryId:"1",type:"S",validation:"none" },
		303: {caption:"[OLD] NOMCBNO",categoryId:"1",type:"S",validation:"none" },
		304: {caption:"[OLD] NOMCGNO",categoryId:"1",type:"S",validation:"none" },
		305: {caption:"[OLD] NOMCDNO",categoryId:"1",type:"S",validation:"none" },
		306: {caption:"[OLD] NOMALNO",categoryId:"1",type:"S",validation:"none" },
		307: {caption:"[OLD] NOMCTMA",categoryId:"1",type:"S",validation:"none" },
		308: {caption:"[OLD] NOMPOMA",categoryId:"1",type:"S",validation:"none" },
		309: {caption:"[OLD] NOMEMMA",categoryId:"1",type:"S",validation:"none" },
		310: {caption:"[OLD] NOMEXMA",categoryId:"1",type:"S",validation:"none" },
		311: {caption:"[OLD] NOMDIMA",categoryId:"1",type:"S",validation:"none" },
		312: {caption:"[OLD] NOMRAMA",categoryId:"1",type:"S",validation:"none" },
		313: {caption:"[OLD] NOMSEMA",categoryId:"1",type:"S",validation:"none" },
		314: {caption:"[OLD] NOMCBMA",categoryId:"1",type:"S",validation:"none" },
		315: {caption:"[OLD] NOMCGMA",categoryId:"1",type:"S",validation:"none" },
		316: {caption:"[OLD] NOMCDMA",categoryId:"1",type:"S",validation:"none" },
		317: {caption:"[OLD] NOMALMA",categoryId:"1",type:"S",validation:"none" },
		318: {caption:"[OLD] NOMCTJU",categoryId:"1",type:"S",validation:"none" },
		319: {caption:"[OLD] NOMPOJU",categoryId:"1",type:"S",validation:"none" },
		320: {caption:"[OLD] NOMEMJU",categoryId:"1",type:"S",validation:"none" },
		321: {caption:"[OLD] NOMEXJU",categoryId:"1",type:"S",validation:"none" },
		322: {caption:"[OLD] NOMDIJU",categoryId:"1",type:"S",validation:"none" },
		323: {caption:"[OLD] NOMRAJU",categoryId:"1",type:"S",validation:"none" },
		324: {caption:"[OLD] NOMSEJU",categoryId:"1",type:"S",validation:"none" },
		325: {caption:"[OLD] NOMCBJU",categoryId:"1",type:"S",validation:"none" },
		326: {caption:"[OLD] NOMCGJU",categoryId:"1",type:"S",validation:"none" },
		327: {caption:"[OLD] NOMCDJU",categoryId:"1",type:"S",validation:"none" },
		328: {caption:"[OLD] NOMALJU",categoryId:"1",type:"S",validation:"none" },
		329: {caption:"[OLD] NOMJU",categoryId:"1",type:"S",validation:"none" },
		330: {caption:"[OLD] NOMNO",categoryId:"1",type:"S",validation:"none" },
		331: {caption:"[OLD] NOMMA",categoryId:"1",type:"S",validation:"none" },
		332: {caption:"[OLD] NOMMO",categoryId:"1",type:"S",validation:"none" },
		333: {caption:"[OLD] NOMCTMO",categoryId:"1",type:"S",validation:"none" },
		334: {caption:"[OLD] NOMPOMO",categoryId:"1",type:"S",validation:"none" },
		335: {caption:"[OLD] NOMEMMO",categoryId:"1",type:"S",validation:"none" },
		336: {caption:"[OLD] NOMEXMO",categoryId:"1",type:"S",validation:"none" },
		337: {caption:"[OLD] NOMDIMO",categoryId:"1",type:"S",validation:"none" },
		338: {caption:"[OLD] NOMRAMO",categoryId:"1",type:"S",validation:"none" },
		339: {caption:"[OLD] NOMSEMO",categoryId:"1",type:"S",validation:"none" },
		340: {caption:"[OLD] NOMCBMO",categoryId:"1",type:"S",validation:"none" },
		341: {caption:"[OLD] NOMCGMO",categoryId:"1",type:"S",validation:"none" },
		342: {caption:"[OLD] NOMCDMO",categoryId:"1",type:"S",validation:"none" },
		343: {caption:"[OLD] NOMALMO",categoryId:"1",type:"S",validation:"none" },
		344: {caption:"[OLD] NOMOL",categoryId:"1",type:"S",validation:"none" },
		345: {caption:"[OLD] NOMCTOL",categoryId:"1",type:"S",validation:"none" },
		346: {caption:"[OLD] NOMPOOL",categoryId:"1",type:"S",validation:"none" },
		347: {caption:"[OLD] NOMEMOL",categoryId:"1",type:"S",validation:"none" },
		348: {caption:"[OLD] NOMEXOL",categoryId:"1",type:"S",validation:"none" },
		349: {caption:"[OLD] NOMDIOL",categoryId:"1",type:"S",validation:"none" },
		350: {caption:"[OLD] NOMRAOL",categoryId:"1",type:"S",validation:"none" },
		351: {caption:"[OLD] NOMSEOL",categoryId:"1",type:"S",validation:"none" },
		352: {caption:"[OLD] NOMCBOL",categoryId:"1",type:"S",validation:"none" },
		353: {caption:"[OLD] NOMCGOL",categoryId:"1",type:"S",validation:"none" },
		354: {caption:"[OLD] NOMCDOL",categoryId:"1",type:"S",validation:"none" },
		355: {caption:"[OLD] NOMALOL",categoryId:"1",type:"S",validation:"none" },
		356: {caption:"[OLD] NOMPI",categoryId:"1",type:"S",validation:"none" },
		357: {caption:"[OLD] NOMCTPI",categoryId:"1",type:"S",validation:"none" },
		358: {caption:"[OLD] NOMPOPI",categoryId:"1",type:"S",validation:"none" },
		359: {caption:"[OLD] NOMEMPI",categoryId:"1",type:"S",validation:"none" },
		360: {caption:"[OLD] NOMEXPI",categoryId:"1",type:"S",validation:"none" },
		361: {caption:"[OLD] NOMDIPI",categoryId:"1",type:"S",validation:"none" },
		362: {caption:"[OLD] NOMRAPI",categoryId:"1",type:"S",validation:"none" },
		363: {caption:"[OLD] NOMSEPI",categoryId:"1",type:"S",validation:"none" },
		364: {caption:"[OLD] NOMCBPI",categoryId:"1",type:"S",validation:"none" },
		365: {caption:"[OLD] NOMCGPI",categoryId:"1",type:"S",validation:"none" },
		366: {caption:"[OLD] NOMCDPI",categoryId:"1",type:"S",validation:"none" },
		367: {caption:"[OLD] NOMALPI",categoryId:"1",type:"S",validation:"none" },
		368: {caption:"[OLD] NOM3",categoryId:"1",type:"S",validation:"none" },
		369: {caption:"[OLD] LON",categoryId:"1",type:"S",validation:"none" },
		370: {caption:"[OLD] ZLREAL",categoryId:"1",type:"S",validation:"none" },
		371: {caption:"[OLD] REPO",categoryId:"1",type:"S",validation:"none" },
		372: {caption:"[OLD] DISPA",categoryId:"1",type:"S",validation:"none" },
		373: {caption:"[OLD] ZSPRID",categoryId:"1",type:"S",validation:"none" },
		374: {caption:"[OLD] IDDIBDB",categoryId:"1",type:"S",validation:"none" },
		400: {caption:"4DL: Identificador",categoryId:"1",type:"I",validation:"none" },
		401: {caption:"4DL: ID (Reservado)",categoryId:"1",type:"I",validation:"none" },
		402: {caption:"4DL: INFRA - Infra. Object ID",categoryId:"1",type:"I",validation:"none" },
		403: {caption:"4DL: INFRA - Ref. Node ID",categoryId:"1",type:"S",validation:"none" },
		404: {caption:"4DL: INFRA - Ref. Infra. Obj.",categoryId:"1",type:"S",validation:"none" },
		405: {caption:"4DL: Posición del Texto",categoryId:"1",type:"S",validation:"none" },
		406: {caption:"Orden Topológico",categoryId:"1",type:"I",validation:"none" },
		407: {caption:"Código de Cliente",categoryId:"1",type:"S",validation:"none" ,customer:"at" },
		408: {caption:"DocumentId",categoryId:"1",type:"I",validation:"none" },
		409: {caption:"NOMctBT",categoryId:"1",type:"S",validation:"none" },
		410: {caption:"Nombre Salida CT BT",categoryId:"1",type:"S",validation:"list" },
		412: {caption:"4DL: ID CT en Nexus",categoryId:"1",type:"S",validation:"none" },
		500: {caption:"Sección completa",categoryId:"1",type:"S",validation:"list" },
		501: {caption:"Doble terna",categoryId:"1",type:"S",validation:"suggested-list" },
		502: {caption:"Postación (Altura y tipo)",categoryId:"1",type:"R",validation:"none" },
		503: {caption:"Fecha de puesta en servicio",categoryId:"1",type:"D",validation:"range" , min:"01/01/1900" , max:"21/04/2026" },
		505: {caption:"Marca",categoryId:"1",type:"S",validation:"none" },
		507: {caption:"Función del conductor",categoryId:"1",type:"S",validation:"list" },
		508: {caption:"Acceso",categoryId:"1",type:"S",validation:"list" },
		509: {caption:"Acceso principal",categoryId:"1",type:"S",validation:"list" },
		510: {caption:"Alarma de presión",categoryId:"1",type:"S",validation:"list" },
		511: {caption:"Domicilio: Altura",categoryId:"1",type:"S",validation:"none" },
		512: {caption:"Amperaje",categoryId:"1",type:"S",validation:"list" },
		513: {caption:"Domicilio: Calle",categoryId:"1",type:"S",validation:"none" },
		514: {caption:"Cantidad de empalmes",categoryId:"1",type:"I",validation:"none" },
		515: {caption:"Ternas involucradas",categoryId:"1",type:"S",validation:"none" },
		517: {caption:"Código de caja",categoryId:"1",type:"S",validation:"none" },
		518: {caption:"Código de empalme",categoryId:"1",type:"S",validation:"none" },
		519: {caption:"Domicilio: Código postal",categoryId:"1",type:"S",validation:"none" },
		521: {caption:"Nivel de criticidad",categoryId:"1",type:"S",validation:"list" },
		523: {caption:"Posee desagote",categoryId:"1",type:"S",validation:"list" },
		524: {caption:"Destino de la salida",categoryId:"1",type:"S",validation:"none" },
		525: {caption:"Disposición de la terna",categoryId:"1",type:"S",validation:"list" },
		526: {caption:"NM: Empresa",categoryId:"1",type:"S",validation:"list" },
		527: {caption:"Domicilio: Entre calle 1",categoryId:"1",type:"S",validation:"none" },
		528: {caption:"Domicilio: Entre calle 2",categoryId:"1",type:"S",validation:"none" },
		529: {caption:"Entre SSEE 1",categoryId:"1",type:"S",validation:"none" },
		530: {caption:"Entre SSEE 2",categoryId:"1",type:"S",validation:"none" },
		531: {caption:"NM: Cant. Enc. Permanente",categoryId:"1",type:"I",validation:"none" },
		532: {caption:"Estado de servicio",categoryId:"1",type:"S",validation:"list" },
		534: {caption:"Flag de servicio (¿Editado?)",categoryId:"1",type:"S",validation:"none" },
		535: {caption:"Lado de apertura",categoryId:"1",type:"S",validation:"list" },
		537: {caption:"Longitud real",categoryId:"1",type:"R",validation:"none" },
		538: {caption:"Material constructivo",categoryId:"1",type:"S",validation:"list" },
		539: {caption:"Material del piquete",categoryId:"1",type:"S",validation:"list" },
		540: {caption:"Cajas: Cantidad Estimada Vías",categoryId:"1",type:"S",validation:"list" },
		541: {caption:"Módulo",categoryId:"1",type:"S",validation:"none" },
		542: {caption:"Municipio No Medidos",categoryId:"1",type:"S",validation:"list" },
		544: {caption:"Nombre de piquete (GMT)",categoryId:"1",type:"S",validation:"none" },
		545: {caption:"Nombre de SSEE",categoryId:"1",type:"S",validation:"none" },
		546: {caption:"Nombre de terna",categoryId:"1",type:"S",validation:"none" },
		547: {caption:"Número CAMESSA",categoryId:"1",type:"S",validation:"none" },
		548: {caption:"Número de CT (GMT)",categoryId:"1",type:"S",validation:"none" },
		549: {caption:"Número de cámara",categoryId:"1",type:"S",validation:"none" },
		550: {caption:"[ELI] Número de suministro",categoryId:"1",type:"S",validation:"none" },
		551: {caption:"Número Elemento Maniobra GMT",categoryId:"1",type:"S",validation:"none" },
		553: {caption:"Plancheta",categoryId:"1",type:"S",validation:"none" },
		554: {caption:"Plano conforme a obra (CaO)",categoryId:"1",type:"S",validation:"none" },
		555: {caption:"Polígono de seguridad",categoryId:"1",type:"S",validation:"list" },
		556: {caption:"Potencia No Medidos",categoryId:"1",type:"S",validation:"list" },
		557: {caption:"Sector de OMSE",categoryId:"1",type:"S",validation:"list" },
		558: {caption:"Subestación de origen",categoryId:"1",type:"S",validation:"none" },
		559: {caption:"Tanques enterrados",categoryId:"1",type:"S",validation:"list" },
		560: {caption:"Teléfono",categoryId:"1",type:"S",validation:"none" },
		561: {caption:"Tensión de servicio",categoryId:"1",type:"S",validation:"suggested-list" },
		562: {caption:"Tensión involucrada",categoryId:"1",type:"S",validation:"list" },
		563: {caption:"Tipo de ICC",categoryId:"1",type:"S",validation:"list" },
		566: {caption:"Tipo de empalme",categoryId:"1",type:"S",validation:"none" },
		567: {caption:"Tipo de mando",categoryId:"1",type:"S",validation:"list" },
		568: {caption:"NM: Tipo de soporte",categoryId:"1",type:"S",validation:"list" },
		569: {caption:"Tipo de zona",categoryId:"1",type:"S",validation:"list" },
		570: {caption:"Tipo de SSEE",categoryId:"1",type:"S",validation:"list" },
		571: {caption:"Tipo de ventilación",categoryId:"1",type:"S",validation:"list" },
		572: {caption:"Tramo",categoryId:"1",type:"S",validation:"none" },
		573: {caption:"Tramo eléctrico",categoryId:"1",type:"S",validation:"none" },
		574: {caption:"Ubicación de la caja",categoryId:"1",type:"S",validation:"list" },
		575: {caption:"Unidad de mantenimiento (UMA)",categoryId:"1",type:"S",validation:"none" },
		576: {caption:"Segmento",categoryId:"1",type:"S",validation:"none" },
		577: {caption:"Sección eléctrica",categoryId:"1",type:"S",validation:"list" },
		578: {caption:"Número de CT (UMT)",categoryId:"1",type:"S",validation:"none" },
		580: {caption:"Número del CT (GBT)",categoryId:"1",type:"S",validation:"none" },
		581: {caption:"Ubicación",categoryId:"1",type:"S",validation:"none" },
		582: {caption:"NM: Cantidad Total",categoryId:"1",type:"I",validation:"none" },
		583: {caption:"NM: Simbología Reservado",categoryId:"1",type:"S",validation:"none" },
		584: {caption:"NM: Cant. Apag. Permanente",categoryId:"1",type:"I",validation:"none" },
		585: {caption:"Domicilio: Departamento",categoryId:"1",type:"S",validation:"none" },
		586: {caption:"Domicilio: Piso",categoryId:"1",type:"S",validation:"none" },
		587: {caption:"Material Conductor",categoryId:"1",type:"S",validation:"list" },
		588: {caption:"Aislación",categoryId:"1",type:"S",validation:"none" },
		589: {caption:"Tipo Constructivo",categoryId:"1",type:"S",validation:"none" },
		590: {caption:"4DL: Nexus MT-BT",categoryId:"1",type:"S",validation:"none" },
		591: {caption:"4DL: MI - Coordenada X",categoryId:"1",type:"S",validation:"none" },
		592: {caption:"4DL: MI - Coordenada Y",categoryId:"1",type:"S",validation:"none" },
		593: {caption:"4DL: MI - Angulo",categoryId:"1",type:"S",validation:"none" },
		594: {caption:"Nombre Plancheta NM",categoryId:"1",type:"S",validation:"none" },
		595: {caption:"Angulo Rotación Plancheta NM",categoryId:"1",type:"R",validation:"range" , min:"0" , max:"360" },
		596: {caption:"Identificador de Grilla",categoryId:"1",type:"S",validation:"none" },
		597: {caption:"Identificador de Grilla al N.",categoryId:"1",type:"S",validation:"none" },
		598: {caption:"Identificador de Grilla al S.",categoryId:"1",type:"S",validation:"none" },
		599: {caption:"Identificador de Grilla al E.",categoryId:"1",type:"S",validation:"none" },
		600: {caption:"Identificador de Grilla al O.",categoryId:"1",type:"S",validation:"none" },
		601: {caption:"Grupo Grilla Lumi",categoryId:"1",type:"S",validation:"none" },
		602: {caption:"ID Carpeta",categoryId:"1",type:"S",validation:"none" },
		603: {caption:"Sumatoria de potencias",categoryId:"1",type:"R",validation:"none" },
		604: {caption:"Numero de CT Unificado Geo",categoryId:"1",type:"S",validation:"none" },
		605: {caption:"UMT: Area Operativa",categoryId:"1",type:"I",validation:"none" },
		606: {caption:"4DL: Nexus AT-MT",categoryId:"1",type:"S",validation:"none" },
		607: {caption:"Código SSEE Unificada Geo",categoryId:"1",type:"S",validation:"none" },
		608: {caption:"Alimentador MT Geo",categoryId:"1",type:"S",validation:"none" },
		609: {caption:"Número Tablero BT CT MI",categoryId:"1",type:"I",validation:"list" },
		610: {caption:"ID Trafo MT/BT GMT",categoryId:"1",type:"S",validation:"none" },
		611: {caption:"ID Trafo MT/BT GBT",categoryId:"1",type:"S",validation:"none" },
		612: {caption:"Tipo Fusible Salida CT",categoryId:"1",type:"S",validation:"list" },
		613: {caption:"ID Trafo AT/MT GAT",categoryId:"1",type:"S",validation:"none" },
		614: {caption:"ID Trafo AT/MT GMT",categoryId:"1",type:"S",validation:"none" },
		615: {caption:"Número Elemento Maniobra GAT",categoryId:"1",type:"S",validation:"none" },
		616: {caption:"Tipo de Entrada Terminal AT",categoryId:"1",type:"S",validation:"list" },
		617: {caption:"Número Elemento Maniobra UMT",categoryId:"1",type:"S",validation:"none" },
		618: {caption:"Datos Geográficos",categoryId:"1",type:"S",validation:"none" },
		621: {caption:"Cantidad de Clientes",categoryId:"1",type:"S",validation:"none" },
		622: {caption:"Número de Medidor",categoryId:"1",type:"S",validation:"none" },
		623: {caption:"Fase",categoryId:"1",type:"S",validation:"suggested-list" },
		624: {caption:"Fases Reparadas",categoryId:"1",type:"S",validation:"suggested-list" },
		625: {caption:"[SIPRE2] Cliente Caja",categoryId:"1",type:"S",validation:"none" },
		626: {caption:"Nombre Hospital",categoryId:"1",type:"S",validation:"none" },
		627: {caption:"Notas Provisorias",categoryId:"1",type:"S",validation:"none" },
		628: {caption:"Nombre Empalme (GAT)",categoryId:"1",type:"S",validation:"none" },
		629: {caption:"Sección Hidráulica (GAT)",categoryId:"1",type:"S",validation:"none" },
		630: {caption:"Descripción Toponimo",categoryId:"1",type:"S",validation:"none" },
		631: {caption:"Tecnología",categoryId:"1",type:"S",validation:"list" },
		632: {caption:"Nombre Extremo AT (GAT)",categoryId:"1",type:"S",validation:"none" },
		633: {caption:"Nombre del Cable (GAT)",categoryId:"1",type:"S",validation:"none" },
		634: {caption:"Nombre del Pórtico (GAT)",categoryId:"1",type:"S",validation:"none" },
		635: {caption:"Nombre del Piquete (GAT)",categoryId:"1",type:"S",validation:"none" },
		636: {caption:"Nom Puesto Interconexión (GAT)",categoryId:"1",type:"S",validation:"none" },
		1000: {caption:"Mayor a 30 caracteres",categoryId:"1",type:"S",validation:"none" },
		1001: {caption:"Color de la Salida",categoryId:"1",type:"S",validation:"list" },
		1003: {caption:"PCM: Material",categoryId:"1",type:"S",validation:"none" },
		1004: {caption:"Código de Manzana",categoryId:"1",type:"S",validation:"none" },
		1005: {caption:"Nombre de Ferrocarril",categoryId:"1",type:"S",validation:"none" },
		1006: {caption:"Nombre de Autopista",categoryId:"1",type:"S",validation:"none" },
		1007: {caption:"Nombre (Hidrografia)",categoryId:"1",type:"S",validation:"none" },
		1008: {caption:"Tiene Transposición",categoryId:"1",type:"S",validation:"suggested-list" },
		1009: {caption:"Nombre Puente al Vuelo (GAT)",categoryId:"1",type:"S",validation:"none" },
		1010: {caption:"4DL: AreaId Batch Plotting",categoryId:"1",type:"I",validation:"none" },
		1011: {caption:"Cantidad (Poda)",categoryId:"1",type:"I",validation:"min" , min:"1" },
		1012: {caption:"PCM: Descripción Material",categoryId:"1",type:"S",validation:"none" },
		1013: {caption:"MIG: Caja",categoryId:"1",type:"S",validation:"none" },
		1014: {caption:"ID Trafo MT/BT UMT",categoryId:"1",type:"S",validation:"none" },
		1015: {caption:"Nombre E/S Centro MT/MT",categoryId:"1",type:"S",validation:"none" },
		1016: {caption:"UNI Prop. de la compañía",categoryId:"1",type:"S",validation:"list" },
		1017: {caption:"UNI Telecontrolado",categoryId:"1",type:"S",validation:"list" },
		1018: {caption:"UNI Identificador Unico Gis",categoryId:"1",type:"S",validation:"none" },
		1019: {caption:"UNI Tipo Constructivo",categoryId:"1",type:"S",validation:"list" },
		1020: {caption:"UNI Fecha de alta",categoryId:"1",type:"D",validation:"none" },
		1026: {caption:"Valorizacion de Instalacion",categoryId:"1",type:"I",validation:"none" },
		1027: {caption:"ID Trafo AT/AT",categoryId:"1",type:"S",validation:"none" },
		1028: {caption:"Sector (GAT)",categoryId:"1",type:"S",validation:"none" },
		1029: {caption:"Secuencia de Fases (GAT)",categoryId:"1",type:"S",validation:"list" },
		1030: {caption:"ID Trafo MT/MT GMT",categoryId:"1",type:"S",validation:"none" },
		1031: {caption:"Salida CT: Nombre Tablero",categoryId:"1",type:"I",validation:"none" },
		1032: {caption:"Migración: Nombre DWG",categoryId:"1",type:"S",validation:"none" },
		1034: {caption:"Cabina Telefónica: Tipo",categoryId:"1",type:"S",validation:"list" },
		1036: {caption:"UNI Tipo de unión",categoryId:"1",type:"S",validation:"none" },
		1037: {caption:"UNI Tipo de Catálogo",categoryId:"1",type:"S",validation:"suggested-list" },
		1039: {caption:"UNI Longitud (Km)",categoryId:"1",type:"R",validation:"none" },
		1041: {caption:"UNI Lugar de instalación",categoryId:"1",type:"S",validation:"none" },
		1042: {caption:"UNI Num. de inventario",categoryId:"1",type:"I",validation:"none" },
		1043: {caption:"UNI Tipo de instalación",categoryId:"1",type:"S",validation:"none" },
		1044: {caption:"UNI Año de fabricación",categoryId:"1",type:"I",validation:"none" },
		1045: {caption:"UNI Referencia",categoryId:"1",type:"S",validation:"none" },
		1047: {caption:"UNI Tipo de elemento DMS",categoryId:"1",type:"S",validation:"none" },
		1049: {caption:"UNI Estado",categoryId:"1",type:"S",validation:"none" },
		1051: {caption:"UNI En servicio",categoryId:"1",type:"S",validation:"none" },
		1052: {caption:"UNI Habilitación de operación",categoryId:"1",type:"S",validation:"none" },
		1053: {caption:"UNI Acc. inibida por protec.",categoryId:"1",type:"S",validation:"none" },
		1054: {caption:"UNI Calidad",categoryId:"1",type:"I",validation:"none" },
		1057: {caption:"UNI Nota",categoryId:"1",type:"S",validation:"none" },
		1062: {caption:"UNI Tipo de &quot;AVR&quot;",categoryId:"1",type:"S",validation:"none" },
		1063: {caption:"UNI Tipo de disp. acum. gases",categoryId:"1",type:"S",validation:"none" },
		1064: {caption:"UNI Tipo de disp. protec. térm",categoryId:"1",type:"S",validation:"none" },
		1065: {caption:"UNI T. de termómetro contacto",categoryId:"1",type:"S",validation:"none" },
		1066: {caption:"UNI Tipo de lubricación",categoryId:"1",type:"S",validation:"none" },
		1068: {caption:"UNI Tipo de aislación",categoryId:"1",type:"S",validation:"none" },
		1070: {caption:"UNI Peso total",categoryId:"1",type:"R",validation:"none" },
		1071: {caption:"UNI Peso de la parte activa",categoryId:"1",type:"R",validation:"none" },
		1072: {caption:"UNI Cantidad de aceite",categoryId:"1",type:"R",validation:"none" },
		1079: {caption:"UNI Existe disp. acum. gases",categoryId:"1",type:"S",validation:"none" },
		1098: {caption:"UNI Tipo de curva de trabajo",categoryId:"1",type:"S",validation:"none" },
		1100: {caption:"UNI Método de arranque",categoryId:"1",type:"S",validation:"none" },
		1101: {caption:"UNI Tipo de curva de eje x",categoryId:"1",type:"S",validation:"none" },
		1121: {caption:"UNI Tipo de línea de suminis.",categoryId:"1",type:"S",validation:"none" },
		1124: {caption:"UNI ID de nivel de tensión",categoryId:"1",type:"S",validation:"none" },
		1143: {caption:"UNI Cont. de actuaciones",categoryId:"1",type:"I",validation:"none" },
		1168: {caption:"UNI Cantidad de Disparos",categoryId:"1",type:"I",validation:"none" },
		1184: {caption:"UNI Número de CT",categoryId:"1",type:"S",validation:"none" },
		1185: {caption:"Número de cuenta Cliente",categoryId:"1",type:"S",validation:"none" },
		1186: {caption:"UNI Razón social",categoryId:"1",type:"S",validation:"none" },
		1187: {caption:"UNI Identificador DMS",categoryId:"1",type:"S",validation:"none" },
		1188: {caption:"Número Trafo AT",categoryId:"1",type:"S",validation:"none" },
		1189: {caption:"Número Trafo",categoryId:"1",type:"S",validation:"none" },
		1190: {caption:"NM: Estado Fuente",categoryId:"1",type:"S",validation:"list" },
		1191: {caption:"NM: Tensión Fuente",categoryId:"1",type:"I",validation:"none" },
		1192: {caption:"NM: Corriente Fuente",categoryId:"1",type:"R",validation:"none" },
		1193: {caption:"NM: Coseno Fi Fuente",categoryId:"1",type:"R",validation:"none" },
		1194: {caption:"UNI Calle",categoryId:"1",type:"S",validation:"none" },
		1195: {caption:"UNI Entre calle 1",categoryId:"1",type:"S",validation:"none" },
		1196: {caption:"UNI Entre calle 2",categoryId:"1",type:"S",validation:"none" },
		1197: {caption:"UNI Localidad/Barrio",categoryId:"1",type:"I",validation:"none" },
		1198: {caption:"Localización",categoryId:"1",type:"S",validation:"none" },
		1199: {caption:"UNI Número de calle",categoryId:"1",type:"S",validation:"none" },
		1200: {caption:"UNI Partido",categoryId:"1",type:"S",validation:"none" },
		1201: {caption:"UNI Potencia contratada",categoryId:"1",type:"S",validation:"none" },
		1202: {caption:"Sección / Sector (GAT)",categoryId:"1",type:"S",validation:"none" },
		1203: {caption:"Nombre Electroducto (GAT)",categoryId:"1",type:"S",validation:"none" },
		1204: {caption:"Desc. Topónimo (Adicional)",categoryId:"1",type:"S",validation:"none" },
		1205: {caption:"ID Servicio",categoryId:"1",type:"I",validation:"none" },
		1206: {caption:"Longitud real prorrateada",categoryId:"1",type:"R",validation:"none" },
		1207: {caption:"4DL: UNI Stopper",categoryId:"1",type:"S",validation:"none" },
		1208: {caption:"UNI Ubicación",categoryId:"1",type:"S",validation:"none" },
		1209: {caption:"UNI Acceso",categoryId:"1",type:"S",validation:"list" },
		1210: {caption:"UNI Fase",categoryId:"1",type:"S",validation:"none" },
		1211: {caption:"UNI Cod. de cliente",categoryId:"1",type:"S",validation:"none" },
		1212: {caption:"Motivo de Empalme",categoryId:"1",type:"S",validation:"suggested-list" },
		1213: {caption:"Rótulo en Campo",categoryId:"1",type:"S",validation:"none" },
		1214: {caption:"[SIPRE2] Calle",categoryId:"1",type:"S",validation:"none" },
		1215: {caption:"[SIPRE2] Altura",categoryId:"1",type:"S",validation:"none" },
		1216: {caption:"[SIPRE2] EntreCalle1",categoryId:"1",type:"S",validation:"none" },
		1217: {caption:"[SIPRE2] EntreCalle2",categoryId:"1",type:"S",validation:"none" },
		1218: {caption:"[SIPRE2] Propiedad",categoryId:"1",type:"S",validation:"none" },
		1219: {caption:"[SIPRE2] Tecnología",categoryId:"1",type:"S",validation:"none" },
		1220: {caption:"Modulo Reducido",categoryId:"1",type:"S",validation:"none" },
		1221: {caption:"CT Afectado",categoryId:"1",type:"S",validation:"none" },
		1222: {caption:"UNI Anormalidades CCR",categoryId:"1",type:"S",validation:"none" },
		1223: {caption:"UNI Anormalidades IGBDE",categoryId:"1",type:"S",validation:"none" },
		1224: {caption:"UNI Cliente",categoryId:"1",type:"S",validation:"none" },
		1225: {caption:"UNI Cliente sensible",categoryId:"1",type:"S",validation:"none" },
		1226: {caption:"UNI Conmutación",categoryId:"1",type:"S",validation:"none" },
		1227: {caption:"UNI Div red - Puntos de interv",categoryId:"1",type:"S",validation:"list" },
		1228: {caption:"UNI Doble terna",categoryId:"1",type:"S",validation:"none" },
		1229: {caption:"UNI Indicador de sección",categoryId:"1",type:"S",validation:"none" },
		1230: {caption:"UNI Medidas de Seguridad",categoryId:"1",type:"S",validation:"none" },
		1231: {caption:"UNI Nivel Penalización",categoryId:"1",type:"S",validation:"none" },
		1232: {caption:"UNI Recierre",categoryId:"1",type:"S",validation:"none" },
		1233: {caption:"UNI Regulación",categoryId:"1",type:"S",validation:"none" },
		1234: {caption:"UNI Semáforo",categoryId:"1",type:"S",validation:"none" },
		1235: {caption:"UNI Tipo de dectector de CC",categoryId:"1",type:"S",validation:"none" },
		1236: {caption:"UNI Tipo de dis. de maniobra",categoryId:"1",type:"S",validation:"none" },
		1237: {caption:"UNI Tipo de transformador",categoryId:"1",type:"S",validation:"none" },
		1238: {caption:"UNI Trabajos en ejecución",categoryId:"1",type:"S",validation:"none" },
		1239: {caption:"UNI Transf. autom. de carga",categoryId:"1",type:"S",validation:"none" },
		1240: {caption:"Fecha estanquización",categoryId:"1",type:"D",validation:"none" },
		1241: {caption:"Fecha impermeabilización",categoryId:"1",type:"D",validation:"none" },
		1242: {caption:"Achique",categoryId:"1",type:"S",validation:"list" },
		1243: {caption:"Tensión de salida BT",categoryId:"1",type:"S",validation:"list" },
		1244: {caption:"Salida CT: CT/Salida",categoryId:"1",type:"S",validation:"none" },
		1245: {caption:"Longitud geométrica",categoryId:"1",type:"R",validation:"none" },
		1246: {caption:"Código Edenor Puente al Vuelo",categoryId:"1",type:"S",validation:"none" },
		1247: {caption:"Tensión de salida MT",categoryId:"1",type:"S",validation:"list" },
		1248: {caption:"UNI Nombre",categoryId:"1",type:"S",validation:"none" },
		1249: {caption:"UNI Capacidad Alimentador",categoryId:"1",type:"R",validation:"none" },
		1250: {caption:"Núm de Elem de Maniobra MI SE",categoryId:"1",type:"S",validation:"none" },
		1251: {caption:"Nombre de CT (unifilar)",categoryId:"1",type:"S",validation:"none" },
		1252: {caption:"V_OMS_DATOGEOGRAFICO",categoryId:"1",type:"S",validation:"none" },
		1253: {caption:"Datos Geográficos (unifilar)",categoryId:"1",type:"S",validation:"none" },
		1254: {caption:"Acceso (unifilar)",categoryId:"1",type:"S",validation:"none" },
		1255: {caption:"Ubicación (unifilar)",categoryId:"1",type:"S",validation:"none" },
		1256: {caption:"Fecha de PS (unifilar)",categoryId:"1",type:"D",validation:"none" },
		1258: {caption:"[SIPRE2] Fecha PS",categoryId:"1",type:"D",validation:"none" },
		1259: {caption:"[SIPRE2] Acceso",categoryId:"1",type:"S",validation:"none" },
		1260: {caption:"[SIPRE2] Ubicación",categoryId:"1",type:"S",validation:"none" },
		1261: {caption:"UNI Identificador DocTec",categoryId:"1",type:"S",validation:"none" },
		1262: {caption:"Nombre Corto Empresa NM",categoryId:"1",type:"S",validation:"none" },
		1263: {caption:"Localidad (Elem Pot)",categoryId:"1",type:"S",validation:"none" },
		1264: {caption:"Datos Geográficos (Elem Pot)",categoryId:"1",type:"S",validation:"none" },
		1265: {caption:"UNI Nombre de alimentador",categoryId:"1",type:"S",validation:"none" },
		1266: {caption:"[SIPRE2] Identificador DocTec",categoryId:"1",type:"S",validation:"none" },
		1267: {caption:"OMS_Tarifa",categoryId:"1",type:"S",validation:"none" },
		1268: {caption:"OMS_Potencia",categoryId:"1",type:"S",validation:"none" },
		1269: {caption:"OMS_Observaciones",categoryId:"1",type:"S",validation:"none" },
		1270: {caption:"OMS_Acceso",categoryId:"1",type:"S",validation:"none" },
		1271: {caption:"OMS_Reiteraciones",categoryId:"1",type:"S",validation:"none" },
		1272: {caption:"Videocámara: Modelo",categoryId:"1",type:"S",validation:"none" },
		1274: {caption:"FO Distancia Real",categoryId:"1",type:"R",validation:"none" },
		1275: {caption:"FO Fecha PS",categoryId:"1",type:"D",validation:"none" },
		1276: {caption:"FO Tipo",categoryId:"1",type:"S",validation:"none" },
		1277: {caption:"FO Identificador",categoryId:"1",type:"S",validation:"none" },
		1278: {caption:"FO Medidas",categoryId:"1",type:"I",validation:"none" },
		1279: {caption:"FO Marca de Ganancia",categoryId:"1",type:"S",validation:"suggested-list" },
		1280: {caption:"FO Profundidad",categoryId:"1",type:"R",validation:"none" },
		1281: {caption:"FO Capacidad",categoryId:"1",type:"I",validation:"suggested-list" },
		1282: {caption:"FO Medidas(largo)",categoryId:"1",type:"I",validation:"none" },
		1283: {caption:"FO Medidas(ancho)",categoryId:"1",type:"I",validation:"none" },
		1284: {caption:"FO Medidas(prof)",categoryId:"1",type:"I",validation:"none" },
		1285: {caption:"4DL: Nexus FO",categoryId:"1",type:"I",validation:"none" },
		1286: {caption:"FO Destino",categoryId:"1",type:"S",validation:"none" },
		1287: {caption:"FO Ganancia",categoryId:"1",type:"R",validation:"none" },
		1288: {caption:"Nombre de CT Geo",categoryId:"1",type:"S",validation:"none" },
		1289: {caption:"Numero de Plano",categoryId:"1",type:"S",validation:"none" },
		1290: {caption:"Pares",categoryId:"1",type:"I",validation:"none" },
		1291: {caption:"Diametro del Cable",categoryId:"1",type:"S",validation:"none" },
		1292: {caption:"ES MANZANA",categoryId:"1",type:"S",validation:"list" },
		1293: {caption:"Codigo de Proyecto",categoryId:"1",type:"I",validation:"none" },
		1294: {caption:"Viento",categoryId:"1",type:"S",validation:"list" },
		1295: {caption:"Tablero",categoryId:"1",type:"S",validation:"list" },
		1296: {caption:"[ELI] CT",categoryId:"1",type:"I",validation:"none" },
		1297: {caption:"Numero de cuenta MI",categoryId:"1",type:"S",validation:"none" },
		1298: {caption:"Numero de Carpeta",categoryId:"1",type:"I",validation:"none" },
		1299: {caption:"Alim_Suministro",categoryId:"1",type:"S",validation:"none" },
		1300: {caption:"NM: Potencia Led",categoryId:"1",type:"S",validation:"list" },
		1301: {caption:"Lado",categoryId:"1",type:"S",validation:"none" },
		1302: {caption:"Tipo Punto Int. Energia",categoryId:"1",type:"S",validation:"list" },
		1500: {caption:"Potencia",categoryId:"1",type:"S",validation:"suggested-list" },
		1501: {caption:"Tipo",categoryId:"1",type:"S",validation:"suggested-list" },
		1502: {caption:"Cantidad",categoryId:"1",type:"I",validation:"none" },
		1600: {caption:"ID SCADA",categoryId:"1",type:"S",validation:"none" },
		1601: {caption:"Agrupador SCADA",categoryId:"1",type:"S",validation:"none" },
		1602: {caption:"Potencia (MVA)",categoryId:"1",type:"R",validation:"none" },
		1603: {caption:"Tension primario",categoryId:"1",type:"R",validation:"none" },
		1604: {caption:"Tension secundario",categoryId:"1",type:"R",validation:"none" },
		1605: {caption:"TensiÃ³n terciario",categoryId:"1",type:"R",validation:"none" },
		1606: {caption:"Localizador",categoryId:"1",type:"S",validation:"none" },
		1607: {caption:"Bahia",categoryId:"1",type:"S",validation:"none" },
		1608: {caption:"Elemento a Reubicar",categoryId:"1",type:"S",validation:"none" },
		1609: {caption:"Potencia (KVA)",categoryId:"1",type:"R",validation:"none" },
		1610: {caption:"Temporal - ID PADRE",categoryId:"1",type:"I",validation:"none" },
		1611: {caption:"Temporal - XY Corte",categoryId:"1",type:"S",validation:"none" },
		1612: {caption:"Temporal - XY Puente",categoryId:"1",type:"S",validation:"none" },
		1613: {caption:"Temporal - XY Tierra",categoryId:"1",type:"S",validation:"none" },
		1614: {caption:"Tipo Parada",categoryId:"1",type:"S",validation:"list" },
		1615: {caption:"Parada Segura",categoryId:"1",type:"S",validation:"list" },
		1630: {caption:"Nombre del temporal BT",categoryId:"1",type:"S",validation:"none" },
		1650: {caption:"Calibre Fusible Real [A]",categoryId:"1",type:"S",validation:"list" },
		1651: {caption:"Calibre Fusible DiseÃ±o [A]",categoryId:"1",type:"S",validation:"list" },
		1652: {caption:"Fecha de VerificaciÃ³n",categoryId:"1",type:"D",validation:"none" },
		1675: {caption:"Nombre o Denominación",categoryId:"0",type:"S",validation:"none" },
		1677: {caption:"SIM",categoryId:"0",type:"S",validation:"none" },
		1679: {caption:"Cantidad de Acometidas",categoryId:"0",type:"I",validation:"none" }
};
PROFILES={
	1: {name:"Predeterminado",description:"Perfil predeterminado"},
	4: {name:"Prueba Ploteo",description:"Perfil para pruebas de ploteo"},
	6: {name:"OMS",description:"Copia del perfil 1 - Predeterminado"},
	7: {name:"AT/MT GEO",description:"Copia del perfil 1 - Predeterminado"},
	8: {name:"Ed.Unifilar",description:"Perfil Edicion Unifilar"}
};
NETTYPES={
		1: {caption:"Cartografía",parent:"0"},
		2: {caption:"Infraestructura MT / BT",parent:"0"},
		3: {caption:"BT Geográfico",parent:"16"},
		5: {caption:"MT Geográfico",parent:"0"},
		6: {caption:"[OLD] MT Unifilar",parent:"0"},
		7: {caption:"AT Geográfico",parent:"0"},
		8: {caption:"[OLD] AT Unifilar",parent:"0"},
		9: {caption:"Telecomunicaciones",parent:"0"},
		10: {caption:"Polígonos de No Medidos",parent:"0"},
		11: {caption:"Polígonos Lumi / Telas",parent:"0"},
		12: {caption:"Carpetas Comerciales",parent:"0"},
		13: {caption:"Poda",parent:"0"},
		14: {caption:"No Medidos",parent:"0"},
		15: {caption:"Infraestructura AT",parent:"0"},
		16: {caption:"Unifilar MT",parent:"22"},
		17: {caption:"Suministros Potenciales",parent:"0"},
		18: {caption:"Fibra Optica",parent:"0"},
		19: {caption:"Infraestructura Fibra Óptica",parent:"0"},
		20: {caption:"Información Proyectos",parent:"0"},
		21: {caption:"Informacion de Carpetas",parent:"0"},
		22: {caption:"Unifilar AT",parent:"0"}};
CATEGORIES={
		1: {caption:"Manzanas",nettypeid:"1"},
		2: {caption:"Veredas",nettypeid:"1"},
		3: {caption:"Secciones de Calle",nettypeid:"1"},
		4: {caption:"Cajas de Distribución",nettypeid:"3"},
		5: {caption:"Líneas Aéreas BT",nettypeid:"3"},
		9: {caption:"Elem. de Maniobra y Protección",nettypeid:"3"},
		10: {caption:"Suministros",nettypeid:"3"},
		11: {caption:"Elem. de Puesta a Tierra",nettypeid:"3"},
		13: {caption:"Elem. de Postación",nettypeid:"3"},
		16: {caption:"Cables Subterráneos BT",nettypeid:"3"},
		23: {caption:"Puentes y Empalmes",nettypeid:"3"},
		28: {caption:"Simbolos Varios",nettypeid:"3"},
		29: {caption:"Líneas Aéreas MT",nettypeid:"5"},
		30: {caption:"Cables Subterráneos MT",nettypeid:"5"},
		33: {caption:"Ctrs. trans., conex. y mixtos",nettypeid:"5"},
		34: {caption:"Elem. de Maniobra y Proteccion",nettypeid:"5"},
		35: {caption:"Elem. de Postación",nettypeid:"5"},
		37: {caption:"Símbolos Varios",nettypeid:"5"},
		38: {caption:"Ctrs. trans., conex. y mixtos",nettypeid:"6"},
		39: {caption:"Elem. de Maniobra y Protección",nettypeid:"6"},
		40: {caption:"Símbolos Varios",nettypeid:"6"},
		41: {caption:"Líneas Aéreas MT",nettypeid:"6"},
		43: {caption:"Cables Subterráneos MT",nettypeid:"6"},
		47: {caption:"Empalmes Trifásicos",nettypeid:"7"},
		48: {caption:"Cámaras",nettypeid:"7"},
		49: {caption:"Subestaciones",nettypeid:"7"},
		50: {caption:"Piquetes",nettypeid:"7"},
		51: {caption:"Empalmes Monofásicos",nettypeid:"7"},
		52: {caption:"Cables AT",nettypeid:"7"},
		53: {caption:"Líneas AT",nettypeid:"7"},
		55: {caption:"Cabinas y Pantallas",nettypeid:"14"},
		56: {caption:"Centros de Transformación",nettypeid:"3"},
		58: {caption:"Luminaria",nettypeid:"14"},
		59: {caption:"Semáforos",nettypeid:"14"},
		60: {caption:"Ctrs. trans., conex. y mixtos",nettypeid:"2"},
		61: {caption:"Ctrs. rebaje, regul. y distr.",nettypeid:"2"},
		62: {caption:"Subestación (AT/MT o AT/AT)",nettypeid:"15"},
		63: {caption:"Líneas de comunicación",nettypeid:"9"},
		64: {caption:"Nodos de conexión",nettypeid:"9"},
		78: {caption:"Media Tensión",nettypeid:"13"},
		79: {caption:"Marcas de Señalización",nettypeid:"5"},
		80: {caption:"Marcas de Señalización",nettypeid:"6"},
		81: {caption:"Símbolos Varios",nettypeid:"7"},
		82: {caption:"Líneas AT",nettypeid:"8"},
		83: {caption:"Cables AT",nettypeid:"8"},
		84: {caption:"Cámaras",nettypeid:"8"},
		85: {caption:"Subestación",nettypeid:"8"},
		86: {caption:"Símbolos Varios",nettypeid:"8"},
		87: {caption:"Accidentes geográficos",nettypeid:"1"},
		88: {caption:"Topónimos",nettypeid:"1"},
		89: {caption:"Trazas Urbanas",nettypeid:"1"},
		91: {caption:"Cables Subt. p/redes 3x220 BT",nettypeid:"3"},
		92: {caption:"Alta Tensión",nettypeid:"13"},
		93: {caption:"Puentes y Empalmes",nettypeid:"5"},
		95: {caption:"Elem. de Puesta a Tierra",nettypeid:"5"},
		96: {caption:"Simbología Condicional",nettypeid:"3"},
		97: {caption:"Simb. Mundo Interno",nettypeid:"3"},
		98: {caption:"Conectores MI",nettypeid:"3"},
		99: {caption:"Polígonos de No Medidos",nettypeid:"10"},
		100: {caption:"Polígonos de Guia Lumi",nettypeid:"11"},
		101: {caption:"Carpetas Comerciales",nettypeid:"12"},
		102: {caption:"Simb. Mundo Interno CT y CC",nettypeid:"5"},
		103: {caption:"Conectores MI",nettypeid:"5"},
		106: {caption:"Puentes al Vuelo",nettypeid:"7"},
		108: {caption:"Camaretas",nettypeid:"7"},
		110: {caption:"Simbolos Mundo Interno",nettypeid:"7"},
		111: {caption:"Conectores MI",nettypeid:"7"},
		112: {caption:"Conectores Provisorios",nettypeid:"3"},
		113: {caption:"Simbolos Provisorios",nettypeid:"3"},
		114: {caption:"Conectores Provisorios",nettypeid:"5"},
		121: {caption:"Nodos",nettypeid:"6"},
		124: {caption:"SE Conectores",nettypeid:"1"},
		125: {caption:"AT Elem. Maniobra y Protección",nettypeid:"22"},
		126: {caption:"AT Conectores/Barras",nettypeid:"22"},
		127: {caption:"AT Trafos SE",nettypeid:"22"},
		128: {caption:"AT Compensadores",nettypeid:"22"},
		129: {caption:"AT Consumo",nettypeid:"22"},
		130: {caption:"AT Fuentes",nettypeid:"22"},
		131: {caption:"AT Salidas",nettypeid:"22"},
		132: {caption:"MT Centros",nettypeid:"16"},
		133: {caption:"MT Elem. Maniobra y Protección",nettypeid:"16"},
		134: {caption:"MT Señalizadores",nettypeid:"16"},
		135: {caption:"MT Conectores/Barras",nettypeid:"16"},
		136: {caption:"MT Salidas",nettypeid:"16"},
		137: {caption:"MT MD Elem. Maniobra y Protec.",nettypeid:"16"},
		138: {caption:"MT MD Conectores/Barras",nettypeid:"16"},
		139: {caption:"MT MD Entradas",nettypeid:"16"},
		140: {caption:"MT Simbolos Varios",nettypeid:"16"},
		141: {caption:"MT Nodos",nettypeid:"16"},
		142: {caption:"AT Nodos",nettypeid:"22"},
		143: {caption:"MT Trafos SE",nettypeid:"16"},
		144: {caption:"AT Simbolos Varios",nettypeid:"22"},
		145: {caption:"MT MD Nodos",nettypeid:"16"},
		146: {caption:"MT MD Trafos",nettypeid:"16"},
		147: {caption:"MT MD Señalizadores",nettypeid:"16"},
		148: {caption:"Empalmes LAT",nettypeid:"7"},
		149: {caption:"Líneas Aéreas 3x220",nettypeid:"3"},
		150: {caption:"AT Lineas de Suministro",nettypeid:"22"},
		151: {caption:"MT MD Simbolos varios",nettypeid:"16"},
		152: {caption:"Simbolos Mundo Interno",nettypeid:"5"},
		153: {caption:"Polígonos de Afectación",nettypeid:"5"},
		154: {caption:"Suministros Potenciales BT",nettypeid:"17"},
		155: {caption:"Suministros Potenciales MTAT",nettypeid:"17"},
		156: {caption:"MT  Lineas de suministro",nettypeid:"16"},
		157: {caption:"Conectores Fibra Óptica",nettypeid:"18"},
		158: {caption:"Postes",nettypeid:"18"},
		159: {caption:"Varios",nettypeid:"18"},
		160: {caption:"Símbolos MI",nettypeid:"18"},
		161: {caption:"Conectores MI",nettypeid:"18"},
		162: {caption:"Otros tendidos y tritubos",nettypeid:"18"},
		163: {caption:"Cajas y Terminales",nettypeid:"19"},
		164: {caption:"Elementos Provisorios",nettypeid:"3"},
		165: {caption:"Polígonos de Proyectos",nettypeid:"20"},
		166: {caption:"Polígonos de Carpetas",nettypeid:"21"}};
